### ISSUE TITLE
error pp_config.rb

### ISSUE THREAD

**Issue by ZkilleMito** [RFX01/PalPal#5]
How to solve this problem, I know it's silly but I don't remember.

pp_config.rb:15:in `initialize': No such file or directory @ rb_sysopen - /home/steam/Steam/steamapps/common/PalServer/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini (Errno::ENOENT)

**Comment by smuhlaci** [comment]
Did you check the path is correct?

rb_config is trying to reach `/home/steam/Steam/steamapps/common/PalServer/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini`.

**Comment by ZkilleMito** [comment]
install steamcmd in linux -__

**Comment by RFX01** [comment]
Theres a section in config.yml that looks like this:

```yaml
# PalServer install path, if you installed it in a different path you will need to change this
PalServerPath: "/home/steam/Steam/steamapps/common/PalServer"
```

This needs to be changed to the path where you installed PalServer.
